baseapp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ddb_webapp/urls.py
from django.contrib import admin
from django.urls import include, path
import baseapp.views


from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.auth import views

urlpatterns = [
    path('', baseapp.views.home, name='home'),
    path('projekt', baseapp.views.projektbeschreibung, name='projektbeschreibung'),
    path('datenschutz', baseapp.views.datenschutz, name='datenschutz'),
    path('kontakt', baseapp.views.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('auswertungen/', include('ddb_showcase.urls_auswertungen')),
    path('daten/', include('ddb_showcase.urls_daten')),
    path('basisdaten/', include('basisdaten.urls')),
    path('login/', views.LoginView.as_view(template_name='baseapp/login.html'), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ddb_showcase/models.py
"""
Definition der Datenbank-Modelle für die **Beteiligungsverfahren**
"""

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


# Partial Date: https://stackoverflow.com/questions/30134526/date-conveniences-validation-display-etc-for-partial-dates-in-django


class BeteiligungsEintrag(models.Model):
    """
    Diese Klasse ist ein Modell, dass Beteiligungsereignisse beschreibt.

    """

    PARTIAL_YEAR='%Y'
    PARTIAL_MONTH='%Y-%m'
    PARTIAL_DAY='%Y-%m-%d'
    PARTIAL_CHOICES = (
      (PARTIAL_YEAR, 'Jahr'),
      (PARTIAL_MONTH, 'Monat'),
      (PARTIAL_DAY, 'Tag'),
    )

    TREFFER_ART_CHOICE = (
        ('1', 'Ankündigung oder Einladung'),
        ('2', 'Bericht oder Zeitungsbericht'),
        ('3', 'Webseite zum Beteiligungsverfahren '),
        ('9', 'Sonstiges'),
        )
    EBENE_CHOICE = (
        ('1', 'Kommunale Ebene'),
        ('2', 'Kommunale Ebene (mehrere Kommunen)'),
        ('3', '(Land-)Kreis-Ebene'),
        ('4', 'regionale Ebene'),
        ('5', 'Landes-Ebene'),
        ('6', 'Bundes-Ebene'),
        ('7', 'europäische Ebene'),
        ('9', 'Sonstiges')
        )
    THEMENGEBIET_CHOICE = (
        ('01', 'Infrastruktur'),
        ('02', 'Keine Festlegung'),
        ('03', 'Umwelt / Energie'),
        ('04', 'Jugend, Soziales, Sport'),
        ('05', 'Mobilität / Verkehr'),
        ('06', 'Bürgerbeteiligung'),
        ('07', 'Finanzen'),
        ('08', 'Migration'),
        ('09', 'Kultur / Bildung'),
        ('10', 'Wirtschaft'),
        ('11', 'Sonstiges'),
        ('12', 'Stadtentwicklung')
        )
    ZIELGRUPPE_CHOICE = (
        ('1', 'Bürger allg. / undefiniert'),
        ('2', 'Anwohner'),
        ('3', 'Betroffene'),
        ('4', 'Kinder, Jugendliche, Schüler'),
        ('5', 'Senioren, Ältere'),
        ('6', 'Migranten'),
        ('7', 'Andere'),
        )
    INITIATOR_CHOICE = (
        ('1', 'Kommunalverwaltung oder Bürgermeister'),
        ('2', 'Behörde oder Amt (nicht Kommunal)'),
        ('3', 'Gemdeinderat, Stadtrat'),
        ('4', 'Partei'),
        ('5', 'Bürgerinitiative'),
        ('6', 'Verband oder Verein'),
        ('7', 'Einzelperson'),
        ('8', 'Unternehmen'),
        ('9', 'Unbekannt / Andere'),
        )
    VALIDIERUNGS_CHOICE = (
        ('not', 'ungeprüfte Rohdaten'),
        ('na1', 'Name in Bezeichnung'),
        ('na1', 'Name in Beschreibung'),
        ('int', 'intern geprüft'),
        ('ext', 'in externer validierung'),
        ('val', 'extern validiert'),
        )

    #kodierauftrag = models.IntegerField()
    gebietseinheit = models.ForeignKey('basisdaten.Gebietseinheit', on_delete=models.PROTECT, 
                                       limit_choices_to={'satzart': '60', 'land': '08'},
                                       help_text="Name der Kommune (sortiert nach Regionalschluessel)")
    #rohtreffer = models.IntegerField()
    andere_rohtreffer = models.CharField(max_length=100, help_text="Doppelte Rohtreffer könenn Sie hier mit KOMMA getrennt eintragen", blank=True, null=True)
    alternative_quelle= models.BooleanField(help_text="Falls die Quelle nicht der eigentliche Rohtreffer war, sondern Sie durch weiterklicken zum Treffer gelangt sin, können Sie hier den eigentlichen Link einfügen, auf dem Sie die Informationen gefunden haben.")
    link_alternative_quelle = models.URLField(max_length=600, blank=True, help_text="Link zur alternativen Quelle")
    treffer_art = models.CharField(max_length=1, verbose_name="Art des Treffers", choices=TREFFER_ART_CHOICE)

    bezeichnung = models.TextField(max_length=150, blank=False, help_text="Wie wird das Beteiligungsverfahren genannt?")
    beschreibung = models.TextField(max_length=1500, blank=False, help_text="Kurzbeschreibung des Beteiligungsverfahrens: Wer, was, wie und warum? (z.B. copy+paste von Webseite)")

    themengebiet =  models.CharField(max_length=2, choices=THEMENGEBIET_CHOICE, help_text="Welches ist das wichtigste Themengebiet")
    weiteres_themengebiet =  models.CharField(max_length=2, choices=THEMENGEBIET_CHOICE, help_text="Gibt es ein weiteres *zentrales* Themengebiet", blank=True, null=True)
    zielgruppe = models.CharField(max_length=1, choices=ZIELGRUPPE_CHOICE, help_text="An wen richtet sich das Beteiligungsverfahren?")
    ebene_zielgruppe = models.CharField(max_length=1,choices=EBENE_CHOICE, help_text="Aus welcher Ebene rekrutieren sich die beteiligten Bürger?")
    initiator = models.CharField(max_length=1,choices=INITIATOR_CHOICE, help_text="Wer hat das Beteiligungsverfahren initiiert")

    start_datum =  models.DateField(blank=False, help_text="Wenn nicht genau bekannt, bitte 'runden' (z.B. 1.7.2017 für Juli 2017)")
    unscharfes_datum = models.CharField('Datum genau auf', choices=PARTIAL_CHOICES, max_length=10,  help_text="Bitte hier angeben für welchen Datumsbereich das Datum gilt")
    end_datum = models.DateField(blank=True, null=True, help_text="Enddatum nur angeben, wenn das Verfahren mehr als einen Tag dauert")
    unscharfes_end_datum = models.CharField('End-Datum genau auf', blank=True, choices=PARTIAL_CHOICES, max_length=10)

    ansprechpartner_name = models.CharField(max_length=50, blank=True, help_text="Initiator / Ansprechpartner wenn bekannt, sonst nur unten Institution angeben")
    ansprechpartner_funktion = models.CharField(max_length=50, blank=True, help_text="Wenn bekannt (z.B. 'Bürgermeister')")
    ansprechpartner_email= models.EmailField(blank=True, help_text="Wenn bekannt")
    ansprechpartner_institution = models.CharField(max_length=255, blank=False, help_text="Bitte genau aungeben, z.B.: 'Grünflächenamt Stadt XYZ' oder 'Bürgerinitiative Windkraft e.v.'")
    
    weitere_dokumentation = models.URLField(blank=True, max_length=600, help_text = "Weblink zu weiterer Dokumentation (z.B. Protokolle, Webseiten etc.).")
    weitere_dokumentation_zusatzfeld_1 = models.URLField(blank=True, max_length=600, help_text = "Weblink zu weiterer Dokumentation (z.B. Protokolle, Webseiten etc.).")
    weitere_dokumentation_zusatzfeld_2 = models.URLField(blank=True, max_length=600, help_text = "Weblink zu weiterer Dokumentation (z.B. Protokolle, Webseiten etc.).")

    kommentar = models.TextField(blank=True, max_length=300, help_text = "Hier können Sie Anmerkungen zur Kodierung hinterlassen")
    validierungstatus = models.CharField(default='not', choices=VALIDIERUNGS_CHOICE, max_length=3)

    #bearbeiter = models.IntegerField()
    stand =  models.DateField(auto_now=True, help_text="Wird automatisch eingetragen")
    erstellt_am =  models.DateField(auto_now_add=True, help_text="Wird automatisch eingetragen")

   
    class Meta:
        abstract = True


class Beteiligungsereignis_Abstract(BeteiligungsEintrag):
    """
    Diese Klasse beschreibt Beteiligungsereignisse.

    Die Klasse erweitert die Base-Klasse BeteiligungsEintrag um Ereignis-spezifische Variablen.
    """

    EBENE_CHOICE = (
        ('1', 'Kommunale Ebene)'),
        ('2', 'Kommunale Ebene (mehrere Kommunen)'),
        ('3', '(Land-)Kreis-Ebene'),
        ('4', 'regionale Ebene'),
        ('5', 'Landes-Ebene'),
        ('6', 'Bundes-Ebene'),
        ('7', 'europäische Ebene'),
        ('9', 'Sonstiges')
        )
    METHODE_CHOICE = (
        ('01', 'Informationsveranstaltung'),
        ('02', 'Workshop, Bürger-, Planungs-, Strategie-, Bilanzwerkstatt'),
        ('03', 'Bürgerforum, Stadtteilforum'),
        ('04', 'Bürgerdialog, Bürgercafé'),
        ('05', 'Umfrage, Befragung, Interviews (online/offline)'),
        ('06', 'Diskussionsveranstaltung'),
        ('07', 'Einwohnerversammlung, Bürgerversammlung'),
        ('08', 'Zukunftskonferenz, Zukunftswerkstatt'),
        ('09', 'Fokusgruppe'),
        ('10', 'World Cafe'),
        ('11', 'Kinder-/Jugendforum, -konferenz, -versammlung, -hearing, -werkstatt'),
        ('12', 'Planauslegung'), 
        ('20', 'Arbeitskreis, Arbeitsgruppe'),
        ('21', 'Stadtteilkonferenz, Bürgerkonferenz'),
        ('22', 'Bürgertisch'),
        ('23', 'Orts-, Nachbarschafts-, Stadteil-, Baustellen, / -begehung, -termin, -rundgang, -spaziergang, Bustour'),
        ('24', 'Runder Tisch'),
        ('25', 'Unterschriftensammlung'),
        ('26', 'Petition'),
        ('27', 'Austausch, Gesprächsrunde, Fragerunde, Sprechstunde'),
        ('28', 'Abschluss- oder Auftaktveranstaltung'),
        ('29', 'Bürgerrat, Bürgerpanel (Zufallsauswahl)'),
        ('30', 'Onlinebeteiligung'),
        ('31', 'Online-Petition'),
        ('70', 'Planfeststellungsverfahren, Stellungnahmen, Einwendung, Erörterung'),  
        ('81', 'Bürgerbegehren'),
        ('82', 'Bürgerentscheid'),
        ('83', 'Einwohnerantrag'),
        ('84', 'Volksbegehren'),
        ('85', 'Volksentscheid'),
        ('97', 'FEHLEINTRAG: XX'),
        ('98', 'FEHLEINTRAG: BE'),
        ('99', 'Andere, und zwar...'),
        )
    BETEILIGUNG_ART_CHOICE = (
        ('0', 'noch nicht kodiert'),
        ('1', 'Art 1'),
        ('2', 'Art 2'),
        ('3', 'Art 3'),
        ('9', 'unklar'),
        )

    sachfrage = models.TextField(max_length=250, blank=False, help_text="Wie lautet die Sachfrage, um die es geht (bitte als Frage formulierern, z.B.: 'Sollen im Ort zwei Windräder gebaut werden?' oder 'Wie soll der Marktplatz umgestaltet werden?'")
    ebene_sachfrage =  models.CharField(max_length=1, choices=EBENE_CHOICE, help_text="Auf welcher politisch-administrativen Ebene wird die Sachfrage entschieden?")
    
    beteiligungsprozess =  models.ForeignKey('Beteiligungsprozess', on_delete=models.PROTECT,
                                       help_text="Ist das Beteiligungsereignis Teil eines größeren Beteiligungsprozesses? Welcher (Prozess muss zuerst angelegt werden)?",
									   blank=True, null=True)
    
    methode = models.CharField(max_length=2,choices=METHODE_CHOICE, help_text="Welche Methode wird genutzt")
    andere_methode = models.CharField(blank=True, max_length=50, help_text="Andere, und zwar...")

ddb_showcase/forms.py
from django import forms
from haystack.forms import HighlightedModelSearchForm


class DateRangeSearchForm(HighlightedModelSearchForm):
    start_date = forms.DateField(required=False)
    end_date = forms.DateField(required=False)


#data = {'q': 'Windenergie OR Windkraft', 'start_date': '2017-01-01', 'end_date': '2017-12-31'}
#a=DateRangeSearchForm(data)
#a.cleaned_data["q"]
#a.is_valid()
#a.cleaned_data["q"]

#sqs1 = a.searchqueryset.auto_query(a.cleaned_data["q"])
#sqs2 = a.searchqueryset.raw_search(a.cleaned_data["q"])
#len(sqs1)
#len(sqs2)

#sqs.result_class()

ddb_showcase/templates/ddb_showcase/beteiligungsereignis.html
{% extends "baseapp/layout.html" %}

{% block extrahead %}
<meta name="robots" content="noindex">
{% endblock %}

{% block content %}


<div class="jumbotron">
<div class="row">
    <div class="col-md-12">
    <h2>{{ title }}</h2>
    <h1>{{ beteiligungsereignis.bezeichnung }}</h1>
    </div>
</div>
    <p>
    {% if beteiligungsereignis.unscharfes_datum == '%Y' %}
    {{ beteiligungsereignis.start_datum|date:'Y' }} 
    {% endif %}
    {% if beteiligungsereignis.unscharfes_datum == '%Y-%m' %}
    {{ beteiligungsereignis.start_datum|date:'M-Y' }} 
    {% endif %}
    {% if beteiligungsereignis.unscharfes_datum == '%Y-%m-%d' %}
    {{ beteiligungsereignis.start_datum|date }} 
    {% endif %}
    {% if beteiligungsereignis.end_datum|date %} bis 
    {% if beteiligungsereignis.unscharfes_end_datum == '%Y' %}
    {{ beteiligungsereignis.end_datum|date:'Y' }} 
    {% endif %}
    {% if beteiligungsereignis.unscharfes_end_datum == '%Y-%m' %}
    {{ beteiligungsereignis.end_datum|date:'F Y' }} 
    {% endif %}
    {% if beteiligungsereignis.unscharfes_end_datum == '%Y-%m-%d' %}
    {{ beteiligungsereignis.end_datum|date }} 
    {% endif %}    
    {% endif %}</p>
    <p><span class="label label-danger">Rohdaten: ungepr&uuml;ft und unbereinigt</span></p>
</div>


<div class="row">
    <div class="col-md-3">
    <p>Themengebiet</p>
    <h5><p>{% if beteiligungsereignis.get_themengebiet_display %}
        <span class="label label-primary">{{  beteiligungsereignis.get_themengebiet_display }}</span>
    {% endif %}
    {% if beteiligungsereignis.get_weiteres_themengebiet_display %}
        <span class="label label-primary">{{  beteiligungsereignis.get_weiteres_themengebiet_display }}</span>
    {% endif %}</p></h5>
    </div>
    <div class="col-md-2">
    <p>Zielgruppe</p>
    <p>{% if beteiligungsereignis.get_zielgruppe_display %}
        <h5><span class="label label-primary">{{  beteiligungsereignis.get_zielgruppe_display }}</span></h5>
    {% endif %}
    </div>
    <div class="col-md-2">
    <p>politische Ebene</p>
    <p>{% if beteiligungsereignis.get_ebene_sachfrage_display %}
        <h5><span class="label label-primary">{{  beteiligungsereignis.get_ebene_sachfrage_display }}</span></h5>
    {% endif %}
    </div>
    <div class="col-md-4">
    </div>
    </div>


<div class="row">
    <div class="col-md-8">
            {% if beteiligungsereignis %}
            <h4>Beschreibung</h4>
            {% if beteiligungsereignis.beteiligungsprozess %}
            <p>Dieses Beteiligungsereignis ist Teil des Beteiligungsprozess 
            <a href="{% url 'beteiligungsprozess' beteiligungsereignis.gebietseinheit_id beteiligungsereignis.beteiligungsprozess.pk %}">{{ beteiligungsereignis.beteiligungsprozess.bezeichnung }}</a>.</p>
            {% endif %}
            <p>{{ beteiligungsereignis.beschreibung }}</p>
            <h4>Sachfrage</h4>
            <p>{{ beteiligungsereignis.sachfrage }}</p>
            <h4>Entscheidung</h4>
            {% if beteiligungsereignis.entscheidung %}
            <p>{{ beteiligungsereignis.entscheidung }}</p>
            {% else %}
            <p>Keine Informationen vorhanden</p>
            {% endif %}
        </br>
        <h4>Weitere Informationen</h4>    
        <table class="table">
            <tr>
                <td>Initiator:</td>
                <td>{{ beteiligungsereignis.get_initiator_display }}</td>
            </tr>
            <tr>
                <td>Angegebenes Beteiligungsformat:</td>
                <td>
                {% if not beteiligungsereignis.get_methode_display == 'Andere, und zwar...' %}
                {{ beteiligungsereignis.get_methode_display }}  
                {% else %}
                {{ beteiligungsereignis.andere_methode }}  
                {% endif %}
                </td>
            </tr>
            <tr>
                <td>Anzahl Teilnehmer:</td>
                <td>
                {% if beteiligungsereignis.anzahl_teilnehmer %}
                {{ beteiligungsereignis.anzahl_teilnehmer }}  
                {% else %}
                keine Information vorhanden
                {% endif %}
                </td>
            </tr>
            <tr>
                <td>Online Komponente:</td>
                <td>
                {% if beteiligungsereignis.online_komponente %}
                Beteiligungsereignis nutzt (auch) online Komponente
                {% else %}
                keine online Komponente vorhanden
                {% endif %}</td>
            </tr>
            </table>

            {% if beteiligungsereignis.weitere_dokumentation %}
            <h4>Weitere Dokumentation (externe Links)</h4>
                <p><a href="{{ beteiligungsereignis.weitere_dokumentation }}" target="_blank"><span class="glyphicon glyphicon-new-window"></span> {{ beteiligungsereignis.weitere_dokumentation|truncatechars:45 }}</span></a></p>
            {% endif %}
            {% if beteiligungsereignis.weitere_dokumentation_zusatzfeld_1 %}
                <p><a href="{{ beteiligungsereignis.weitere_dokumentation_zusatzfeld_1 }}" target="_blank"><span class="glyphicon glyphicon-new-window"></span> {{ beteiligungsereignis.weitere_dokumentation_zusatzfeld_1|truncatechars:45 }}</span></a></p>
            {% endif %}
            {% if beteiligungsereignis.weitere_dokumentation_zusatzfeld_2 %}
                <p><a href="{{ beteiligungsereignis.weitere_dokumentation_zusatzfeld_2 }}" target="_blank"><span class="glyphicon glyphicon-new-window"></span> {{ beteiligungsereignis.weitere_dokumentation_zusatzfeld_2|truncatechars:45 }}</span></a></p>
            {% endif %}

            {% endif %}
            
    </div>


    <div class="col-md-4">
            <div class="col-md-12">
            <div class="well">
                <a href="{% url 'gemeindeansicht' beteiligungsereignis.gebietseinheit_id %}"> <img src="{{ infobox_erweiterung.wappen.url }}" alt="Wappen {{ infobox_erweiterung.ortsname_suche }}" width="100" align="right"></a>
                <h3>{{ infobox_erweiterung.ortsname_suche }} </h3>
                <p>{{ infobox.get_textkennzeichen_display }} im Kreis {{ infobox.kreisname }} ({{ infobox.landname }})</p>
                <p>Regionalsschl&uuml;ssel: {{ infobox.regionalschluessel }}</p>
                

                <h4>Gemeindeverwaltung:</h4>
                <p>{{ infobox_erweiterung.strasse_gv }}</br>
                {{ infobox_erweiterung.plz_ort_gv }}</br>
                {% if user.is_authenticated %}
                <span class="glyphicon glyphicon-envelope"></span> <a href="mailto:{{ infobox_erweiterung.mail_gv }}">{{ infobox_erweiterung.mail_gv }}</a></br>
                {% else %}
                <span class="glyphicon glyphicon-envelope"></span> <em>E-Mail-Adresse nach Anmeldung sichtbar</em></br>
                {% endif %}
                <span class="glyphicon glyphicon-globe"></span> <a href="{{ infobox_erweiterung.homepage_gv }}" target="blank">{{ infobox_erweiterung.homepage_gv }}</a></p>


                {% if user.is_authenticated %}
                <h4>Ansprechpartner:</h4>
                <p>{{ infobox_erweiterung.get_ansprechpartner_anrede_display }} {{ infobox_erweiterung.ansprechpartner_vorname }} {{ infobox_erweiterung.ansprechpartner_name }}</br>
                    {{ infobox_erweiterung.ansprechpartner_funktion }}</br>
                    <span class="glyphicon glyphicon-envelope"></span> <a href="mailto:{{ infobox_erweiterung.ansprechpartner_mail }}">{{ infobox_erweiterung.ansprechpartner_mail }}</a></br>
                    <span class="glyphicon glyphicon-earphone"></span> {{ infobox_erweiterung.ansprechpartner_telefon }}</p>
                {% else %}
                {% endif %}

                <h4>Basisdaten:</h4>
                <p>Einwohner: {{ infobox.bevoelkerung }} ({{ infobox.bevolkerungsdichte }} pro km<sup>2</sup>)</br>
                Fl&auml;che: {{ infobox.flaeche }} km<sup>2</sup></br>
                Urbanisierungsgrad: {{ infobox.get_verstaedterung_display }}</br>
</div>
            </div>
        </div>
 </div>

<div class="row">
    <div class="col-md-12">
        </br>
    <p><a class="btn btn-default" href="{% url 'gemeindeansicht' beteiligungsereignis.gebietseinheit_id %}">Zur&uuml;ck zur Gesamt&uuml;bersicht {{ infobox_erweiterung.ortsname_suche }} &raquo;</a></p>
    </div>
</div>


            
{% endblock %}

ddb_showcase/templates/ddb_showcase/index.html
{% extends "baseapp/layout.html" %}


{% block content %}

<div class="jumbotron">
    <h1>{{title}}</h1>
    <p class="lead">Nutzen Sie die Volltextsuche um nach Gemeinden, Beteiligungsprojekten oder Beteiligungsereignissen in Baden-W&uuml;rttemberg zu suchen.</p>

        <p><em>Beteiligungsereignisse</em> sind die 'Grundeinheit' der Beteiligung. Ein Ereignis ist eine zeitlich abgrenzbare
        Beteiligungsveranstaltung oder andere Form der Beteiligung.  Es kann Teil eines &uuml;bergeordneten Beteiligungsprojektes sein, aber 
        auch als Einzeleregnis auftreten. <em>Beteiligungsprojekte</em> bestehen aus mehreren Beteiligungsereignissen, die &uuml;ber eine 
        gemeinsame Sachfrage miteinander verbunden sind. </p>
</div>



<div class="container">
            <div class="row">    

</div>

    <form method="get" action=".">
        <div class="row">    
            <div class="col-xs-8">
                <p class="small">Die Suchbegriffe werden automatisch mit <code>AND</code> verkn&uuml;pft. Mit <code>OR</code> lassen sich Sie verschiedene Begriffe gleichzeitig suchen. 
                Ein Stern <code>*</code> kann als Platzhalter genutzt werden. Mit <code>NOT</code> lassen sich Begriffe ausschlie&szlig;en. Text in Anf&uuml;rungszeichen <code>"..."</code> wird als exakter Ausdruck gesucht.</p>
		        <div class="input-group">
                    <div class="input-group-prepend">
                    <span class="input-group-text">
                        <span class="fa fa-search fa-lg"></span> 
                    </span> 
                    </div>
                    <input id="id_q" type="text" class="form-control" name="q" placeholder="suche nach...">
                    <div class="input-group-append">
                    <button class="btn btn-outline-secondary btn-sm" type="submit">Suchen</button>
                </div>
                </div>
            </div>
        </div>

        <div class="row">
            <p></p>
            </div>
        <div class="row">
        {% if query %}
            <h4>Suchergebnisse</h4>
            </div>
            <div class="row">
            <p>Die Suche nach <em>"{{ query }}"</em> ergab <span class="badge badge-pill badge-secondary">{{ page_obj.paginator.count }}</span> Treffer.</p>
            </div>

            <div class="row">  
                <ul class="list-group list-group-flush">
                    {% for result in page_obj.object_list %}
                        <li class="list-group-item pb-0">
                        {% if result.object.regionalschluessel %}
                            <p><small>Gemeinde</small></br>
                            <a href="{% url 'gemeindeansicht' result.object.pk  %}">{{ result.object.name }}: {{ result.object.get_textkennzeichen_display }}</a></br>
                            </p>
                        {% else %}
                            <p><small>Beteiligungsereignis</small></br>
                            <a href="{% url 'beteiligungsereignis' result.object.gebietseinheit_id result.object.pk %}">{{ result.object.gebietseinheit.name }}: {{ result.object.bezeichnung }}</a></br>
                            {{ result.object.start_datum }} - {{ result.object.beschreibung|truncatechars:140 }}</p>
                        {% endif %}     

                        {% endfor %}
                        </li>
                    </ul>
                </div>
            <div class="row"> 
                        {% if page_obj.has_previous or page_obj.has_next %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?q={{ query }}&amp;page=1">&laquo; Erste</a></li>
            <li class="page-item"><a class="page-link" href="?q={{ query }}&amp;page={{ page_obj.previous_page_number }}">zur&uuml;ck</a></li>
        {% endif %}

        <li class="page-item active">
            <a class="page-link">Seite {{ page_obj.number }} von {{ page_obj.paginator.num_pages }}</a>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?q={{ query }}&amp;page={{ page_obj.next_page_number }}">n&auml;chste</a></li>
            <li class="page-item"><a class="page-link" href="?q={{ query }}&amp;page={{ page_obj.paginator.num_pages }}">Letzte &raquo;</a></li>
        {% endif %}
    </ul>
                <div>
</div>


                        {% endif %}
                        {% else %}
        {% endif %}
                
                </div>
    </form>
</div>

{% endblock %}